version: "2"
services:
  zookeeper:
    image: quay.io/debezium/zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - kafka-net
    container_name: zookeeper
  kafka:
    image: quay.io/debezium/kafka
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - kafka-net
    container_name: kafka
    depends_on:
      - zookeeper
  mysql-main:
    image: quay.io/debezium/example-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=secret
    networks:
      - kafka-net
    container_name: mysql-main
  mongo-replica:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - kafka-net
    container_name: mongo-replica
  connect:
    build: .
    ports:
      - 8083:8083
    networks:
      - kafka-net
    container_name: connect
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_GROUP_ID=1
      - GROUP_ID=1
      - CONNECT_PLUGIN_PATH=/kafka/connect, /home/kafka/.local/libs
      - CONNECT_CONFIG_STORAGE_TOPIC=my-connect-onfigs
      - CONNECT_OFFSET_STORAGE_TOPIC=my-connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=my-source-connect-statuses
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect
      - CONNECT_REST_PORT=8083
      - CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components
    depends_on:
      - kafka
      - mysql-main

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
